name: Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build CLI
        run: |
          # Compile for different platforms
          bun build ./src/index.ts --compile --outfile carbon-linux
          bun build ./src/index.ts --compile --outfile carbon-macos --target darwin
          bun build ./src/index.ts --compile --outfile carbon-windows.exe --target win32

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            carbon-linux
            carbon-macos
            carbon-windows.exe
          draft: false
          prerelease: false
          generate_release_notes: true